/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 17 09:52:28 GMT 2024
 */

package com.tts;

import org.junit.Test;
import static org.junit.Assert.*;
import com.tts.Dog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Dog_ESTest extends Dog_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.bark();
  }
}
