/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 17 09:22:24 GMT 2024
 */

package com.tts;

import org.junit.Test;
import static org.junit.Assert.*;
import com.tts.Mail;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Mail_ESTest extends Mail_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Mail mail0 = new Mail((String) null, "", "", (String) null);
      assertFalse(mail0.isRead());
      
      mail0.markAsRead();
      boolean boolean0 = mail0.isRead();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Mail mail0 = new Mail("", "", (String) null, (String) null);
      String string0 = mail0.getSubject();
      assertFalse(mail0.isRead());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Mail mail0 = new Mail("WL.g=yz/[=LT", "", "WL.g=yz/[=LT", "");
      String string0 = mail0.getSubject();
      assertEquals("WL.g=yz/[=LT", mail0.getSender());
      assertEquals("", mail0.getRecipient());
      assertEquals("WL.g=yz/[=LT", string0);
      assertEquals("", mail0.getBody());
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Mail mail0 = new Mail((String) null, (String) null, (String) null, (String) null);
      mail0.getSender();
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Mail mail0 = new Mail("z", "z", "z", "z");
      mail0.getSender();
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Mail mail0 = new Mail((String) null, (String) null, (String) null, (String) null);
      mail0.getRecipient();
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Mail mail0 = new Mail("", "", "^Sj9P0rp@:=8aHDk", (String) null);
      String string0 = mail0.getRecipient();
      assertNotNull(string0);
      assertEquals("^Sj9P0rp@:=8aHDk", mail0.getSubject());
      assertFalse(mail0.isRead());
      assertEquals("", mail0.getSender());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Mail mail0 = new Mail("^10`R%'|uLvuq;o7oIK", "", "", "");
      String string0 = mail0.getBody();
      assertEquals("^10`R%'|uLvuq;o7oIK", mail0.getSender());
      assertEquals("", mail0.getRecipient());
      assertEquals("", string0);
      assertFalse(mail0.isRead());
      assertEquals("", mail0.getSubject());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Mail mail0 = new Mail("lr5P(", "lr5P(", "lr5P(", "lr5P(");
      String string0 = mail0.toString();
      assertEquals("Mail from: lr5P(\nTo: lr5P(\nSubject: lr5P(\nRead: false", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Mail mail0 = new Mail("KED'`NR98aIq'`K", "EEUFk6@\"1KH6", "KED'`NR98aIq'`K", "EEUFk6@\"1KH6");
      assertEquals("KED'`NR98aIq'`K", mail0.getSender());
      
      mail0.setSender("EEUFk6@\"1KH6");
      assertEquals("EEUFk6@\"1KH6", mail0.getRecipient());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Mail mail0 = new Mail("KED'`NR98aIq'`K", "EEUFk6@\"1KH6", "KED'`NR98aIq'`K", "EEUFk6@\"1KH6");
      assertEquals("EEUFk6@\"1KH6", mail0.getBody());
      
      mail0.setBody((String) null);
      mail0.getBody();
      assertFalse(mail0.isRead());
      assertEquals("EEUFk6@\"1KH6", mail0.getRecipient());
      assertEquals("KED'`NR98aIq'`K", mail0.getSubject());
      assertEquals("KED'`NR98aIq'`K", mail0.getSender());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Mail mail0 = new Mail("KED'`NR98aIq'`K", "EEUFk6@\"1KH6", "KED'`NR98aIq'`K", "EEUFk6@\"1KH6");
      assertEquals("KED'`NR98aIq'`K", mail0.getSubject());
      
      mail0.setSubject("KED'`NR98aIq'`K");
      assertEquals("EEUFk6@\"1KH6", mail0.getBody());
      assertEquals("KED'`NR98aIq'`K", mail0.getSender());
      assertEquals("EEUFk6@\"1KH6", mail0.getRecipient());
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Mail mail0 = new Mail("", "", "^Sj9P0rp@:=8aHDk", (String) null);
      assertEquals("", mail0.getRecipient());
      
      mail0.setRecipient("");
      assertEquals("", mail0.getSender());
      assertFalse(mail0.isRead());
      assertEquals("^Sj9P0rp@:=8aHDk", mail0.getSubject());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Mail mail0 = new Mail("", "", "^Sj9P0rp@:=8aHDk", (String) null);
      String string0 = mail0.getSender();
      assertEquals("^Sj9P0rp@:=8aHDk", mail0.getSubject());
      assertEquals("", string0);
      assertEquals("", mail0.getRecipient());
      assertFalse(mail0.isRead());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Mail mail0 = new Mail("", "", "", "");
      boolean boolean0 = mail0.isRead();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Mail mail0 = new Mail("KED'`NR98aIq'`K", "EEUFk6@\"1KH6", "KED'`NR98aIq'`K", "EEUFk6@\"1KH6");
      String string0 = mail0.getRecipient();
      assertEquals("EEUFk6@\"1KH6", mail0.getBody());
      assertEquals("EEUFk6@\"1KH6", string0);
      assertEquals("KED'`NR98aIq'`K", mail0.getSubject());
      assertEquals("KED'`NR98aIq'`K", mail0.getSender());
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Mail mail0 = new Mail("", "", "", "");
      mail0.getSubject();
      assertFalse(mail0.isRead());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Mail mail0 = new Mail("KED'`NR98aIq'`K", "EEUFk6@\"1KH6", "KED'`NR98aIq'`K", "EEUFk6@\"1KH6");
      String string0 = mail0.getBody();
      assertFalse(mail0.isRead());
      assertEquals("KED'`NR98aIq'`K", mail0.getSubject());
      assertEquals("EEUFk6@\"1KH6", mail0.getRecipient());
      assertEquals("KED'`NR98aIq'`K", mail0.getSender());
      assertEquals("EEUFk6@\"1KH6", string0);
  }
}
